# Generated by Django 4.2.14 on 2024-10-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartment', '0004_remove_contract_apartment_remove_contract_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='tuDo',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Resident')], null=True),
        ),
    ]
