# Generated by Django 4.2.14 on 2024-10-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartment', '0005_notification_remove_user_tudo_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'WAITING'), (1, 'RECEIVED')], default=0, null=True),
        ),
    ]
